<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nginx_memcached"
 *
 * Auto generated by Extension Builder 2014-11-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'nginx memcached',
	'description' => 'Adds a page-cache which is accessible by the memcached module from nginx.',
	'category' => 'misc',
	'author' => 'Philipp Bergsmann',
	'author_email' => 'p.bergsmann@opendo.at',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);